# Generated by Django 4.2.13 on 2024-06-04 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sito', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='preparationtime',
            field=models.CharField(blank=True, help_text='Totale tempo di preparazione (es: 1 hour 30 minutes)', max_length=200, null=True),
        ),
    ]
