# Generated by Django 4.2.13 on 2024-06-05 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sito', '0002_alter_recipe_preparationtime'),
    ]

    operations = [
        migrations.RenameField(
            model_name='follow',
            old_name='follower',
            new_name='utente',
        ),
        migrations.AlterUniqueTogether(
            name='follow',
            unique_together={('utente', 'followee')},
        ),
    ]
